server:  port: 9082  
spring:
#  thymeleaf:
#    prefix: classpath:/static/, classpath:/templates/
#    suffix: .html
  resources:
    static-locations: classpath:/static/, classpath:/templates/    logging:  level:    root: info    error:  whitelabel:    enabled: false---    config-attributes:  value: 345                         #对应单个值  valueArray: 1,2,3,4,5,6,7,8,9      #对应数组  valueList:                         #对应list    -13579    -246810  valueMap:                          #对应map    name: lili    age: 20    sex: female  valueMapList:                      #对应list<map>    - name: bob      age: 21    - name: caven      age: 31      