server:  port: 9082  
spring:
#  thymeleaf:
#    prefix: classpath:/static/, classpath:/templates/
#    suffix: .html
  resources:
    static-locations: classpath:/static/, classpath:/templates/    logging:  level:    root: info    error:  whitelabel:    enabled: false    